export const categoryResourceData = {
  top_id: null,
  slug: 'all',
  parent_id: null,
  name: 'All',
  meta_title: null,
  meta_description: null,
  images: null,
  description: null,
  id: '667427827a36c72a34b4fda2',
  children: {
    page: 1,
    count: 0,
    results: [],
    page_count: 1,
    limit: 1000,
  },
  products: {
    page: 1,
    count: 2,
    results: [
      {
        id: '654a5dc14aee444bb17fc245',
        attributes: {
          color: {
            visible: false,
            name: 'color',
            id: 'color',
            filterable: true,
            value: ['red', 'blue', 'green'],
          },
        },
        currency: 'USD',
        description: 'Bladiebladiebladie<br><br>',
        bundle: null,
        images: [
          {
            id: '65f03e5f208d9c4ead189351',
            file: {
              height: 681,
              md5: 'c8bf87634a628c45b6582de05d710762',
              url: 'http://cdn.swell.test/test_test/65f03e45208d9c4ead18931f/c8bf87634a628c45b6582de05d710762',
              width: 1024,
            },
          },
          {
            id: '65f03eb3208d9c4ead189508',
            file: {
              height: 681,
              md5: 'c8bf87634a628c45b6582de05d710762',
              url: 'http://cdn.swell.test/test_test/65f03eb1208d9c4ead1894e3/c8bf87634a628c45b6582de05d710762',
              width: 1024,
            },
          },
          {
            id: '65fac20700a96f93dc5e1c2a',
            file: {
              height: 1820,
              md5: '602498f4d8cf6d3c59d2dd96f4bc77e9',
              url: 'http://cdn.swell.test/test_test/65fac20500a96f93dc5e1c1d/602498f4d8cf6d3c59d2dd96f4bc77e9',
              width: 3840,
            },
          },
        ],
        meta_description: null,
        meta_title: null,
        name: 'test product\\!!! (copy) (copy)',
        options: [
          {
            id: '653a5da40cfa51dd9b9e5c68',
            name: 'color',
            values: [
              { id: '653a5dac0cfa51dd9b9e5c69', name: 'red' },
              { id: '653a5dac0cfa51dd9b9e5c6a', name: 'blue' },
              { id: '653a5dac0cfa51dd9b9e5c6b', name: 'green' },
            ],
            variant: true,
            input_type: 'select',
            required: true,
            active: true,
            attribute_id: 'color',
          },
        ],
        price: 12,
        purchase_options: {
          standard: { price: 12, sale: false, sale_price: null },
        },
        sale: false,
        sku: null,
        slug: 'test-product-copy-copy',
        stock_status: null,
        stock_tracking: false,
        tags: [],
        categories: [],
      },
      {
        id: '653a5dac527b804ca76f477f',
        attributes: {},
        currency: 'USD',
        description: 'Bladiebladiebladie<br><br>',
        bundle: null,
        images: [
          {
            id: '653a61db527b804ca76f54d1',
            file: {
              height: 1182,
              md5: '29bc995ab4d2a2773a3af6aabc5b2baa',
              url: 'http://cdn.swell.test/test_test/653a61f7527b804ca76f556a/29bc995ab4d2a2773a3af6aabc5b2baa',
              width: 665,
            },
          },
        ],
        meta_description: null,
        meta_title: null,
        name: 'test product\\!!!',
        options: [],
        price: 12,
        purchase_options: {
          standard: { price: 12, sale: false, sale_price: 10 },
        },
        sale: false,
        sku: null,
        slug: 'test-product',
        stock_purchasable: false,
        stock_status: null,
        stock_tracking: false,
        tags: [],
        categories: [],
      },
    ],
    page_count: 1,
    limit: 15,
    filter_options: [
      {
        id: 'color',
        label: 'color',
        type: 'select',
        options: [
          { value: 'red', label: 'red', count: 1, active: false },
          { value: 'blue', label: 'blue', count: 1, active: false },
          { value: 'green', label: 'green', count: 1, active: false },
        ],
        param_name: 'filter_color',
        active_options: [],
        inactive_options: [
          { value: 'red', label: 'red', count: 1, active: false },
          { value: 'blue', label: 'blue', count: 1, active: false },
          { value: 'green', label: 'green', count: 1, active: false },
        ],
      },
    ],
  },
  sort: '',
  sort_options: [
    { value: '', name: 'Featured' },
    {
      value: 'popularity',
      name: 'Popularity',
      query: 'popularity desc',
    },
    {
      value: 'price_asc',
      name: 'Price, low to high',
      query: 'price asc',
    },
    {
      value: 'price_desc',
      name: 'Price, high to low',
      query: 'price desc',
    },
    { value: 'date_asc', name: 'Date, old to new', query: 'date asc' },
    {
      value: 'date_desc',
      name: 'Date, new to old',
      query: 'date desc',
    },
    { value: 'name_asc', name: 'Product name, A-Z', query: 'name asc' },
    {
      value: 'name_desc',
      name: 'Product name, Z-A',
      query: 'name desc',
    },
  ],
};
